import {validateGrid,neighbors,pathCost,coordsOf} from "./grid.js";
class Heap{constructor(){this.items=[];this.serial=0;}less(a,b){return a.f<b.f||(a.f===b.f&&a.order<b.order);}push(node,g,f){const x={node,g,f,order:this.serial++},a=this.items;a.push(x);let i=a.length-1;while(i){const p=(i-1)>>1;if(!this.less(a[i],a[p]))break;[a[i],a[p]]=[a[p],a[i]];i=p;}}pop(){const a=this.items,first=a[0],last=a.pop();if(a.length){a[0]=last;let i=0;for(;;){let j=i,l=2*i+1,r=l+1;if(l<a.length&&this.less(a[l],a[j]))j=l;if(r<a.length&&this.less(a[r],a[j]))j=r;if(j===i)break;[a[i],a[j]]=[a[j],a[i]];i=j;}}return first;}peek(){return this.items[0];}}
function reconstruct(parent,start,goal){const path=[];for(let p=goal;p!==-1;p=parent[p]){path.push(p);if(p===start)break;}path.reverse();return path[0]===start?path:[];}
function heuristic(grid,a,b){const A=coordsOf(grid,a),B=coordsOf(grid,b);return Math.abs(A.x-B.x)+Math.abs(A.y-B.y);}
function uni(grid,start,goal,algorithm){const g=validateGrid(grid),n=g.cells.length;if(![start,goal].every(i=>Number.isInteger(i)&&i>=0&&i<n&&g.cells[i]))throw new Error("endpoint");if(start===goal)return {found:true,cost:0,path:[start],visited:[start],algorithm};const dist=new Float64Array(n).fill(Infinity),parent=new Int32Array(n).fill(-1),closed=new Uint8Array(n),visited=[],heap=new Heap();dist[start]=0;heap.push(start,0,algorithm==="astar"?heuristic(g,start,goal):0);while(heap.items.length){const {node:u,g:du}=heap.pop();if(closed[u]||du!==dist[u])continue;closed[u]=1;visited.push(u);if(u===goal){const path=reconstruct(parent,start,goal);return {found:true,cost:du,path,visited,algorithm};}for(const v of neighbors(g,u)){if(closed[v])continue;const nd=du+g.cells[v];if(nd<dist[v]){dist[v]=nd;parent[v]=u;heap.push(v,nd,nd+(algorithm==="astar"?heuristic(g,v,goal):0));}}}return {found:false,cost:null,path:[],visited,algorithm};}
function cleanTop(heap,dist,closed){while(heap.items.length){const x=heap.peek();if(closed[x.node]||x.g!==dist[x.node])heap.pop();else return x.g;}return Infinity;}
export function bidirectionalDijkstra(grid,start,goal){const g=validateGrid(grid),n=g.cells.length;if(![start,goal].every(i=>Number.isInteger(i)&&i>=0&&i<n&&g.cells[i]))throw new Error("endpoint");if(start===goal)return {found:true,cost:0,path:[start],visited:[start],algorithm:"bidijkstra"};const df=new Float64Array(n).fill(Infinity),db=new Float64Array(n).fill(Infinity),pf=new Int32Array(n).fill(-1),nextb=new Int32Array(n).fill(-1),cf=new Uint8Array(n),cb=new Uint8Array(n),hf=new Heap(),hb=new Heap(),vf=[],vb=[];df[start]=0;db[goal]=0;hf.push(start,0,0);hb.push(goal,0,0);let best=Infinity,meet=-1;const consider=v=>{if(Number.isFinite(df[v])&&Number.isFinite(db[v])){const c=df[v]+db[v];if(c<best||(c===best&&(meet<0||v<meet))){best=c;meet=v;}}};while(hf.items.length&&hb.items.length){const minF=cleanTop(hf,df,cf),minB=cleanTop(hb,db,cb);if(!Number.isFinite(minF)||!Number.isFinite(minB))break;if(best<Infinity&&minF+minB>=best)break;if(minF<=minB){const {node:u,g:du}=hf.pop();if(cf[u]||du!==df[u])continue;cf[u]=1;vf.push(u);consider(u);for(const v of neighbors(g,u)){if(cf[v])continue;const nd=du+g.cells[v];if(nd<df[v]){df[v]=nd;pf[v]=u;hf.push(v,nd,nd);consider(v);}}}else{const {node:u,g:du}=hb.pop();if(cb[u]||du!==db[u])continue;cb[u]=1;vb.push(u);consider(u);for(const v of neighbors(g,u)){if(cb[v])continue;const nd=du+g.cells[u];if(nd<db[v]){db[v]=nd;nextb[v]=u;hb.push(v,nd,nd);consider(v);}}}}
if(meet<0)return {found:false,cost:null,path:[],visited:[...vf,...vb],algorithm:"bidijkstra"};const left=reconstruct(pf,start,meet),right=[];for(let p=nextb[meet];p!==-1;p=nextb[p]){right.push(p);if(p===goal)break;}const path=[...left,...right];if(path.at(-1)!==goal)return {found:false,cost:null,path:[],visited:[...vf,...vb],algorithm:"bidijkstra"};return {found:true,cost:pathCost(g,path),path,visited:[...vf,...vb.filter(x=>!vf.includes(x))],algorithm:"bidijkstra"};}
export function shortestPath(grid,start,goal,algorithm="astar"){if(algorithm==="bidijkstra")return bidirectionalDijkstra(grid,start,goal);if(!["astar","dijkstra"].includes(algorithm))throw new Error("algorithm");return uni(grid,start,goal,algorithm);}
export function createDistanceOracle(grid,algorithm="astar"){const g=validateGrid(grid),cache=new Map();return {get(a,b){const key=`${a}:${b}`;if(cache.has(key))return cache.get(key);const r=shortestPath(g,a,b,algorithm);cache.set(key,r);return r;},cacheSize(){return cache.size;}};}
