import {parseScenario,serializeScenario} from "./io/scenario.js";
import {classifySkus} from "./domain/sku.js";
import {generateOrders} from "./domain/orders.js";
import {currentAssignments,optimizeSlotting} from "./slotting/optimizer.js";
import {compareLayouts} from "./simulation/compare.js";
const $=id=>document.getElementById(id);let scenario=null,optimized=null,lastReport=null;
function mapify(x){return x instanceof Map?x:new Map(Object.entries(x));}
function download(name,text){const b=new Blob([text],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function renderMap(svg,warehouse,skus,assignments,route=null){const {grid,depot,slots}=warehouse,w=grid.width,h=grid.height,cellW=900/w,cellH=600/h,bySlot=new Map(),map=mapify(assignments);for(const sku of skus)bySlot.set(map.get(sku.sku),sku.sku);let body="";for(let i=0;i<grid.cells.length;i++){const x=(i%w)*cellW,y=Math.floor(i/w)*cellH,fill=grid.cells[i]?"#23364d":"#0d121a";body+=`<rect x="${x+1}" y="${y+1}" width="${cellW-2}" height="${cellH-2}" rx="5" fill="${fill}"/>`;}if(route){const points=[];for(const seg of route.segments)for(const i of seg.path){const x=(i%w)*cellW+cellW/2,y=Math.floor(i/w)*cellH+cellH/2;points.push(`${x},${y}`);}body+=`<polyline points="${points.join(" ")}" fill="none" stroke="#7ee2b8" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" opacity=".9"/>`;}for(const slot of slots){const x=(slot.index%w)*cellW,y=Math.floor(slot.index/w)*cellH,sku=bySlot.get(slot.id),fill=slot.zone==="cold"?"#b99cff":"#8ad7ff";body+=`<rect x="${x+5}" y="${y+5}" width="${cellW-10}" height="${cellH-10}" rx="7" fill="${fill}"/><text x="${x+cellW/2}" y="${y+cellH/2+4}" text-anchor="middle" font-size="12" fill="#07111d">${sku??slot.id}</text>`;}const dx=(depot%w)*cellW,dy=Math.floor(depot/w)*cellH;body+=`<circle cx="${dx+cellW/2}" cy="${dy+cellH/2}" r="${Math.min(cellW,cellH)*.3}" fill="#ffd27d"/><text x="${dx+cellW/2}" y="${dy+cellH/2+4}" text-anchor="middle" font-size="11" fill="#07111d">D</text>`;svg.innerHTML=body;}
function renderStatic(){const cls=classifySkus(scenario.skus),curr=currentAssignments(scenario.skus),opt=optimized.assignments;$("scenarioName").textContent=scenario.name;$("scenarioStats").textContent=`${scenario.warehouse.grid.width}×${scenario.warehouse.grid.height} grid · ${scenario.warehouse.slots.length} slots · ${scenario.skus.length} SKUs`;renderMap($("currentMap"),scenario.warehouse,scenario.skus,curr);renderMap($("suggestedMap"),scenario.warehouse,scenario.skus,opt);const counts={A:0,B:0,C:0};for(const x of cls)counts[x.abc]++;$("aCount").textContent=counts.A;$("bCount").textContent=counts.B;$("cCount").textContent=counts.C;const clsMap=new Map(cls.map(x=>[x.sku,x]));$("slotTable").innerHTML=optimized.details.map(d=>{const s=clsMap.get(d.sku);return `<tr><td>${d.sku}</td><td>${s.abc}${s.xyz}</td><td>${s.slotId}</td><td>${d.slotId}</td><td>${d.distance}</td></tr>`;}).join("");}
function runSimulation(){const orders=generateOrders(scenario.skus,{count:Number($("orderCount").value),seed:Number($("seed").value),maxLines:Number($("maxLines").value)}),curr=currentAssignments(scenario.skus),algorithm=$("algorithm").value,report=compareLayouts(scenario.warehouse,scenario.skus,orders,curr,optimized.assignments,{algorithm});lastReport={scenario:scenario.name,generatedAt:new Date().toISOString(),orderConfig:{count:orders.length,seed:Number($("seed").value),maxLines:Number($("maxLines").value)},report};$("avg").textContent=`${report.before.mean.toFixed(1)} → ${report.after.mean.toFixed(1)}`;$("median").textContent=`${report.before.median.toFixed(1)} → ${report.after.median.toFixed(1)}`;$("p95").textContent=`${report.before.p95.toFixed(1)} → ${report.after.p95.toFixed(1)}`;$("reduction").textContent=`${(100*report.reduction).toFixed(1)}%`;$("outcomes").textContent=`${report.improved} · ${report.unchanged} · ${report.worsened}`;$("orderTable").innerHTML=report.perOrder.slice(0,10).map((x,i)=>`<tr><td>${x.id}</td><td>${orders[i].skus.join(", ")}</td><td>${x.before}</td><td>${x.after}</td><td>${x.delta}</td></tr>`).join("");const first=report.perOrder[0];$("replayText").textContent=`${first.id}: ${first.afterRoute.sequence.join(" → ")} → depot · cost ${first.after}`;renderMap($("replayMap"),scenario.warehouse,scenario.skus,optimized.assignments,first.afterRoute);}
$("run").onclick=runSimulation;$("exportReport").onclick=()=>{if(lastReport)download("warehouse-flow-report.json",JSON.stringify(lastReport,null,2)+"\n");};$("exportScenario").onclick=()=>scenario&&download("warehouse-flow-scenario.json",serializeScenario(scenario));
const raw=await fetch("./examples/warehouse-scenario.json").then(r=>{if(!r.ok)throw new Error("scenario-load");return r.text();});scenario=parseScenario(raw);optimized=optimizeSlotting(scenario.warehouse,scenario.skus);renderStatic();runSimulation();
